### ISSUE TITLE
Issue with fava in docker and https

### ISSUE THREAD

**Issue by grostim** [beancount/fava#1027]
Hi,
I am not really sure if this issue is related to fava or to my setup.

I have fava running in a docker container. It is exposed to internet through traefik which is also dealing with https and oauth2 authentication.

Fava is overall running well and at first i had no issues.
However since a couple of days i have noticed the folowing problem:
When i try to import statement files i a blank popup that appear.
by using the "inspect" tools of Chrome, i can see the following error:
(Please note that although i have noticed the issue a couple of days ago, it might be much older... I have been sloppy in my bookeeping for the last two months :D)

> /comptes-famille-gros/import/:1 Mixed Content: The page at 'https://fava.famillegros.com/comptes-famille-gros/import/' was loaded over HTTPS, but requested an insecure resource 'http://fava.famillegros.com/comptes-famille-gros/api/changed/'. This request has been blocked; the content must be served over HTTPS.

This error code keeps repeating every second while i am on the "import" page.

Is it normal that this ressource "http://fava.famillegros.com/comptes-famille-gros/api/changed/" is not called through https ?

If that may help, here is my docker-compose file
```
## This docker-compose file is designed to be used as a template in portainer.
##
## This template can be set up in your portainer "App template".
## Don't forget to set the following environment variables:
## - DOMAIN => your DNS domainname ( example.com )
## - OAUTH2_PROXY_CLIENT_ID => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_CLIENT_SECRET => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_COOKIE_SECRET => Some random long string

version: "3.0"

services:
  fava:
    image: grostim/fava-docker:latest
    volumes:
      - $MYDIR/fava:/myData
      - $MYDIR/fava/cron.daily:/etc/cron.daily/fava
      - $MYDIR/.ssh:/root/.ssh
      - $MYDIR/.gitconfig:/root/.gitconfig
    networks:
      - internal
    environment:
      - BEANCOUNT_INPUT_FILE=/myData/Famille.beancount
      - FAVA_HOST="0.0.0.0"
      - FAVA_DEBUG=True
      - ALPHAVANTAGE_API_KEY=$ALPHAVANTAGE_API_KEY
      - QUANDL_API_KEY=$QUANDL_API_KEY
      - IEX_TOKEN=$IEX_TOKEN
    deploy:

  fava-proxy:
    image: a5huynh/oauth2_proxy
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:fava.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/volumes/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://fava:5000
      -redirect-url=https://fava.$DOMAIN
      -http-address=http://0.0.0.0:4180
      -email-domain=$DOMAIN
      -provider=google
      -authenticated-emails-file=/authenticated-emails.txt
    environment:
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.2.0/24
```
