### ISSUE TITLE
allow wrapping all text fields

### ISSUE THREAD

**Issue by maxheld83** [beancount/fava#1826]
I sometimes find it useful to be able to see text fields (notes, but also narrations etc) *wrapped*, like so:

```css
.journal .description {
  flex: 1;
  padding-left: 8px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: normal;
}
```

It would be nice to switch this easily in the UI or options.
